# general
seed: 42
workers: 8
#dataset_dir: "./datasets"
task_no: t1

# train options
batch_size: 256
image_size: 224
start_epoch: 60
epochs: 1000
dataset: "mcc" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
cats: 68
# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/mcc_20_48"
reload: True

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
