# general
seed: 42
workers: 8
#dataset_dir: "./datasets"
# train options
batch_size: 256
image_size: 224
start_epoch: 180
epochs: 300
dataset: "mcc" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
cats: 80
# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/t1_new_5"
reload: True

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
