_BASE_: "../../Base-RCNN-C4-OWDet.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "./output/t2_ft_10/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_ft_10', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (50000, 60000)
  MAX_ITER: 74000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_ft_10"
OWDet:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  CLUSTERING:
    START_ITER: 18000
